// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDowN9U0fHVze6QJ_jV1JStoE_BZUc-CXI',
    appId: '1:575897638372:web:767441e1d12459570ee3f1',
    messagingSenderId: '575897638372',
    projectId: 'swift-shop-1',
    authDomain: 'swift-shop-1.firebaseapp.com',
    storageBucket: 'swift-shop-1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMx3Dsl2odK2Gtt1moEMbajfevfm_lV8M',
    appId: '1:575897638372:android:178992ded6491e650ee3f1',
    messagingSenderId: '575897638372',
    projectId: 'swift-shop-1',
    storageBucket: 'swift-shop-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBplZWJvgxWeljPvQGPLQjGmV2VR7imcCI',
    appId: '1:575897638372:ios:be680d7f0ac7f9df0ee3f1',
    messagingSenderId: '575897638372',
    projectId: 'swift-shop-1',
    storageBucket: 'swift-shop-1.firebasestorage.app',
    iosBundleId: 'com.example.swiftShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBplZWJvgxWeljPvQGPLQjGmV2VR7imcCI',
    appId: '1:575897638372:ios:be680d7f0ac7f9df0ee3f1',
    messagingSenderId: '575897638372',
    projectId: 'swift-shop-1',
    storageBucket: 'swift-shop-1.firebasestorage.app',
    iosBundleId: 'com.example.swiftShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDowN9U0fHVze6QJ_jV1JStoE_BZUc-CXI',
    appId: '1:575897638372:web:b4b11b149d30a4950ee3f1',
    messagingSenderId: '575897638372',
    projectId: 'swift-shop-1',
    authDomain: 'swift-shop-1.firebaseapp.com',
    storageBucket: 'swift-shop-1.firebasestorage.app',
  );
}
